spring:
  datasource:
    url: jdbc:h2:file:~/.h2/testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database: h2
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
  data:
    mongodb:
      uri: mongodb://csdn:Luncert428@luncert.cn:27017/csdn